### PR TITLE
Follow https://github.com/Gesto/javascript#18.3

### PR DESCRIPTION
**Pull request by jpringle**

### CODE REVIEW

**Comment by reaganthomas** [comment]
I'd rather change the style guide on this one if no one minds.

**Comment by jpringle** [comment]
Personally I find ```if (x < y)``` easier to read than ```if(x < y)``` but I will bow to the will of the masses.

**Comment by joshua-gesto** [comment]
@jpringle: Agreed. I don't think GitHub charges per space (or linefeed, for that matter), so I don't see any reason to be so sparing with their use.

**Comment by reaganthomas** [comment]
We've been doing it the other way and no one said anything...I'd prefer to leave it

**Comment by joshua-gesto** [comment]
I might have said something if I had realized it was open for discussion.

Although I have my own ideas about what makes for good formatting and readability, I don't feel strongly about it -- certainly not so much that I would go about making unnecessary changes to the formatting of code that I am not otherwise working on.

In any event, like Jason, I'll go with whatever the majority decides.

**Comment by jpringle** [comment]
Any dissent?  None?  Make it so.

**Pull request merged**
