### PR TITLE
Add end_with_newline to HTML and Javascript config

### PR DESCRIPTION
**Pull request by jpringle**

### CODE REVIEW

**Comment by reaganthomas** [comment]
:+1:

**Comment by prestonvanloon** [comment]
I don't care either way, but can someone answer why it's preferred to have a new line at the end of every file?

**Comment by reaganthomas** [comment]
http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

It's an old standard. I also like it because it lets you scroll more at the bottom, but atom has a setting that trumps that.

**Comment by prestonvanloon** [comment]
Totally makes sense when you're using `cat` for files. :+1:

**Comment by reaganthomas** [comment]
I think git used to do it automatically if I'm not mistaken. Somewhere along the line though they got more flexible.

**Pull request merged**
